# Generated by Django 3.2.4 on 2021-07-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210702_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='email',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
