# Generated by Django 3.2.4 on 2021-07-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_books_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='file',
            field=models.FileField(blank=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='books',
            name='teacher',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
